# Generated by Django 4.1.7 on 2023-03-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['issue_date']},
        ),
    ]
